food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    path('food/<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('add',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

foodwebsite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from menu import views as menu_views
from contact import views as contact_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.forms import LoginForm

urlpatterns = [
    path('',include('food.urls')),
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html',authentication_form=LoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('contact/',contact_views.contact,name='contact'),
    path('menu/',menu_views.menu,name='menu'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from . import views
from django.urls import path
from menu import views as menu_views

app_name = 'menu'
urlpatterns = [
    path('menu/',menu_views.menu,name='menu'),
]

users/urls.py
from django.urls import path
from ..foodwebsite import settings
from users import views as user_views
from django.contrib.auth import views as auth_views
from users.forms import LoginForm

appname = 'users'
urlpatterns = [
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html',authentication_form=LoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
]

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):

    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=500)

    def __str__(self):
        return self.email

food/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://img.freepik.com/darmowe-zdjecie/widok-z-gory-pizzy-pepperoni-z-pieczarek-kielbasy-papryka-oliwka-i-kukurydza-na-czarny-drewniany_141793-2158.jpg?w=2000")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

menu/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_manager = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username 

contact/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      self.fields['username'].help_text=''
      self.fields['email'].help_text=''
      self.fields['password1'].help_text=''
      self.fields['password2'].help_text=''

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text=''
        self.fields['password'].help_text=''

contact/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from foodwebsite.settings import EMAIL_HOST_USER

def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = 'Website Inquiry' 
			body = {
			'full_name': form.cleaned_data['full_name'], 
			'email': form.cleaned_data['email'], 
            'subject': form.cleaned_data['subject'],
			'message': form.cleaned_data['message'], 
			}
			message = "\n".join(body.values())

			try:
				send_mail(subject, message, body['email'], [EMAIL_HOST_USER], fail_silently=False) 
			except BadHeaderError:
				return HttpResponse('Invalid header found')
			return redirect ("food:index")
      
	form = ContactForm()
	return render(request, "contact/contact.html", {'form':form})

food/views.py
from django.shortcuts import render, redirect
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/details.html'
 
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

    def dispatch(self, request):
        in_group =  self.request.user.groups.filter(name='Staff').exists()
        return in_group

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['in_group'] =  self.request.user.groups.filter(name='Staff').exists()
        return context

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',{'item':item})

menu/views.py
from django.shortcuts import render

# Create your views here.

def menu(request):

    return render(request,'menu/menu.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account has been created')
            return redirect('login')
    else:
        form = RegisterForm()

    return render(request,'users/register.html',{'form':form})

contact/templates/contact/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=chrome">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Contact</title>
        <link rel="stylesheet" href="{% static 'contact/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body style="background-image: url('/pictures/register-bg.jpeg'); background-size: cover; height: 100vh; min-height: 60vh; position: relative;">
      <body>
      <nav class="navbar navbar-expand-lg navbar-align-items-left navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'food:index' %}">Yellow Dragon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-expand-sm ml-auto" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              {% if user.is_authenticated %}
              {% if in_group %}
              <a class="nav-link active" href="{% url 'food:create_item' %}">Add Item</a>
            </li>
            {% endif %}
            {% endif %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'menu' %}">Menu</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'register' %}">Register</a>
            </li>
          </ul>
            {% endif %}
        </div>
      </nav>
        {% block body %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body> 
</html>

contact/templates/contact/contact.html
{% extends 'contact/base.html' %}
{% block body %}
<div class="container-fluid mx-auto vertical-center" style="width: 80rem;">
        <div id="contact-card" class="card mx-auto rounded-0" style="width: 40rem; height: 45rem">
            <div class="card-body">
                <h1 class="text-center mt-4 mb-4" id="contact-h1">Contact Us</h1>
                <p class="text-center text-white">If you have a question for us, please leave a message.</p>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group mt-5 pt-3">
                      <input type="text" class="form-control text-white" name="full_name" id="{{ form.full_name.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="text" class="label-name">
                        <span class="content-name">Full Name</span>
                      </label>
                    </div>
                    <div class="form-group mt-5 mx-auto">
                      <input type="email" class="form-control text-white" name="email" id="{{ form.email.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="email" class="label-name">
                        <span class="content-name">Email</span>
                      </label>
                    </div>
                    <div class="form-group mt-5 mx-auto">
                      <input type="text" class="form-control text-white" name="subject" id="{{ form.subject.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="text" class="label-name">
                        <span class="content-name">Subject</span>
                      </label>
                    </div>
                    <div class="form-group mt-5 mx-auto">
                      <textarea class="form-control text-white" name="message" id="{{ form.message.id_for_label }}" type="text" rows="4" autocomplete="off" placeholder="" required></textarea>
                      <label for="text" class="label-name" id="textarea-label">
                        <span class="content-name" id="textarea-span">Message</span>
                      </label>
                      </div>
                      <div class="container">
                    <button type="submit" class="btn text-black rounded-0 bg mt-5">Submit</button>
                    </div>
                  </form>
            </div>
        </div>
    </div>
{% endblock %}

food/templates/food/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food website</title>
    <link href="https://fonts.googleapis.com/css?family=Nosifer:regular" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Parisienne:regular" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-align-items-left navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'food:index' %}">Bloody Good</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-expand-sm ml-auto" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'food:create_item' %}">Add Item</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">View Item</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'register' %}">Register</a>
            </li>
          </ul>
            {% endif %}
        </div>
      </nav>
    {% block body %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body> 
</html>

food/templates/food/details.html
{% extends 'food\base.html' %}

{% block body %}
<div class="container">
<div class="row">
<div class="col-md-6">
<img src="{{ item.item_image }}" height="300px" class="card mx-auto mt-2">
</div>
<div class="col-md-6 mt-5">
<h1>{{ object.item_name }}</h1>
<h2>{{ object.item_desc }}</h2>
<h3>${{ object.item_price }}</h3>
<h3>
<a href="{% url 'food:update_item' item.id %}">Update</a>
<a href="{% url 'food:delete_item' item.id %}">Delete</a>
</h3>
</div>
</div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food\base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food website</title>
</head>
<body>
{% block body %}
{% if messages %}
    {% for message in messages %}
    <div id="message">
    <div style="padding: 0px;">
    <div class="alert alert-success{{ message.tag }}">
        {{ message }}
    </div>
</div>
</div>
    {% endfor %}
{% endif %}
{% for item in item_list %}
<div class="row no-gutters mr-5">
        <img class="card ml-auto mr-5 mt-2" height="140px" src="{{ item.item_image }}">
<div class="col-md-3">
    <h1>{{ item.item_name }}</h3>
    <h2>{{ item.item_desc }}</h2>
    <h3>${{ item.item_price }}</h2>
</div>
<div class="col-md-2 mt-5">
    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
</div>
</div>
{% endfor %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

food/templates/food/item-delete.html
{% extends 'food\base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <div class="container text-center mt-2" style="width: 30%">
    <h2>Are you sure you want to delete {{ item.item_name }}?</h2>
    <button type="submit" class="btn btn-danger mt-4">Delete</button>
    </div>
</form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food\base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <div class="container mt-2">
    {{ form }}
    </div>
    <div class="col-md-12 text-center">
    <button type="submit" class="btn btn-primary mt-4">Submit</button>
    </div>
</form>
{% endblock %}

menu/templates/menu/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food website</title>
    <link href="https://fonts.googleapis.com/css?family=Nosifer:regular" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Parisienne:regular" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-align-items-left navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'food:index' %}">Bloody Good</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-expand-sm ml-auto" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'food:create_item' %}">Add Item</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'menu' %}">Menu</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link active" href="{% url 'register' %}">Register</a>
            </li>
          </ul>
            {% endif %}
        </div>
      </nav>
    {% block body %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body> 
</html>

menu/templates/menu/menu.html
{% extends 'menu\base.html' %}
{% block body %}
{% endblock %}

users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=chrome">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Register</title>
        <link rel="stylesheet" href="{% static 'users/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body style="background-image: url('/pictures/register-bg.jpeg'); background-size: cover; height: 100vh; min-height: 60vh; position: relative;">
        {% block body %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body> 
</html>

users/templates/users/login.html
{% extends 'users\base.html' %}
{% block body %}
<div class="container" id="login-container" style="width: 50rem; height: 45rem;">
    <div id="login-card" class="card mx-auto rounded-0" style="width: 30rem; height: 25rem;">
        <div class="card-body">
          <h1 class="text-center mt-4 mb-4" id="login-h1">Sign in</h1>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group mt-2 p-3">
                  <input type="text" class="form-control text-white" name="username" id="{{ form.username.id_for_label }}" autocomplete="off" placeholder="" required />
                  <label for="text" class="label-name">
                    <span class="content-name">Username</span>
                  </label>
                </div>
                <div class="form-group mt-2 p-3">
                  <input type="password" class="form-control text-white" name="password" id="{{ form.password.id_for_label }}" autocomplete="off" placeholder="" required />
                  <label for="password" class="label-name">
                    <span class="content-name">Password</span>
                  </label>
                </div> 
                <div class="col text-center">
                <button type="submit" class="btn text-black rounded-0 mt-5 mx-auto">Sign In</button>
              </div>
              </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users\base.html' %}
{% block body %}
<div class="container-fluid mx-auto vertical-center" style="width: 80rem;">
    <div class="left-container" style="width: 40rem; height: 45rem;">
            <h1 class="text-center" id="register-text">CREATE ACCOUNT NOW</h1>
    </div>
    <div class="right-container" style="width: 40rem; height: 45rem;">
        <div id="card-right" class="card mx-auto rounded-0" style="width: 40rem; height: 45rem">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group mt-5 pt-3">
                      <input type="text" class="form-control text-white" name="username" id="{{ form.username.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="text" class="label-name">
                        <span class="content-name">Username</span>
                      </label>
                    </div>
                    <div class="form-group mt-5 mx-auto">
                      <input type="email" class="form-control text-white" name="email" id="{{ form.email.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="email" class="label-name">
                        <span class="content-name">Email</span>
                      </label>
                    </div>
                    <div class="form-group mt-5 mx-auto">
                      <input type="password" class="form-control text-white" name="password1" id="{{ form.password.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="password1" class="label-name">
                        <span class="content-name">Password</span>
                      </label>
                    </div>
                    <div class="form-group mt-5 mx-auto">
                      <input type="password" class="form-control text-white" name="password2" id="{{ form.password2.id_for_label }}" autocomplete="off" placeholder="" required />
                      <label for="password2" class="label-name">
                        <span class="content-name">Confirm Password</span>
                      </label>
                      </div>
                      <div class="container">
                    <button type="submit" class="btn text-black rounded-0 bg mt-5">Sign Up</button>
                    </div>
                  </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}